CREATE TABLE IF NOT EXISTS ttest (
    x integer
);

CREATE FUNCTION trigf() RETURNS trigger
    AS 'MODULE_PATHNAME'
    LANGUAGE C;

CREATE TRIGGER tbefore BEFORE INSERT OR UPDATE OR DELETE ON ttest
    FOR EACH ROW EXECUTE FUNCTION trigf();

CREATE TRIGGER tafter AFTER INSERT OR UPDATE OR DELETE ON ttest
    FOR EACH ROW EXECUTE FUNCTION trigf();